version: "3.8"
services:
  app:
    image: kooldev/php:7.4-nginx
    ports:
     - "${KOOL_HTTP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:cached
    #  - $HOME/.ssh:/home/kool/.ssh:cached
    networks:
     - kool_local
     - kool_global
  database:
    image: mysql:8.0 # can change to: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password # remove this line if you change to: mysql:5.7
    ports:
     - "${KOOL_DATABASE_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-rootpass}"
      MYSQL_DATABASE: "${DB_DATABASE:-database}"
      MYSQL_USER: "${DB_USERNAME:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
     - db:/var/lib/mysql:cached
    networks:
     - kool_local
     - kool_global
  cache:
    image: redis:alpine
    volumes:
     - cache:/data:cached

volumes:
  db:
  cache:

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
